server:
  port: 8888

spring:
  application:
    name: plant-config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LminWoo99/PlantCloudConfig.git
          username: LminWoo99
          password: '{cipher}AQB7vD46GLjSHXRj1OZBIQTI3PieTlTZD3e9bGo0c94tWYOS4BfodZtd4UjBGTYrgQsD+T/ybDm8L7YDpMhWg/JfqY9KAQSl9GYalurvFGIuJCckOKLM5pmIk3EGyfhPbE++65Y8JIYa9U6MZTffBUmvLzG0PBKQ4U6cO3DH3tRXRApJu3q8q7kttSrhDBPPKdw/jW6X6kx20TaoGhrSy9UmP/EtkJdFmqCoZDMx/IabtbNhSDxXFrQBLP1uBEkYk5l7SQp3fYSrjxWZWHjJwFhfOtpiW3xG5Tua9AnIV8GaVubAaPDZQWkcjVZflr/mornpNmOdGw+ptOLgYuS/PKejU5zKOEmhoAnuUnMDuqhE+lfzHo8h2IKgEJqwMNhnVvd86DyhPLUZSsmMGBrSBkRE3/KXVjA0ZPkpr7aoq+XDdg=='

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
