server:
  port: 8761
spring:
  application:
    name: plant-eureka
  cloud:
    config:
      uri : http://43.202.205.242:8888
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://43.202.205.242:8761/eureka

