#
## workflow의 이름
#name: PLANT
#
## 해당 workflow가 언제 실행될 것인지에 대한 트리거를 지정
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#
## workflow는 한개 이상의 job을 가지며, 각 job은 여러 step에 따라 단계를 나눌 수 있습니다.
#jobs:
#  build:
#    name: PLANT
#    # 해당 jobs에서 아래의 steps들이 어떠한 환경에서 실행될 것인지를 지정합니다.
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'zulu'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew
#        shell: bash
#
#      - name: Build with Gradle
#        run: ./gradlew build
#        shell: bash
